version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - citus

  citus_master:
  # docker exec -it citus_master psql -U postgres -d hpdm_db -c "\dt"
    image: citusdata/citus:latest
    container_name: citus_master
    environment:
      POSTGRES_DB: hpdm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    depends_on:
      - citus_worker
    networks:
      - citus

  citus_worker:
    image: citusdata/citus:latest
    environment:
      POSTGRES_DB: hpdm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - citus
    
  backend:
    image: hpdm_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@citus_master:5432/hpdm_db?schema=public"
      JWT_SECRET: ~secretik~
    deploy:
      update_config:
          parallelism: 2
          delay: 10s
    depends_on:
      - citus_master
    networks:
      - citus

networks:
  citus:
    driver: bridge

# docker-compose up -d --scale backend=2 --scale citus_worker=2

# 
# # Get the names of the worker containers
# docker ps --filter "name=citus_worker" --format "{{.Names}}"

# in range of NODES:
#   docker exec -it citus_master psql -U postgres -d hpdm_db -c "SELECT master_add_node('hpdm-citus_worker-{node}, 5432);"
# 